// <auto-generated />
using CoordinatorsMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoordinatorsMicroservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220908073517_ChangedDataTypeFromLongToString")]
    partial class ChangedDataTypeFromLongToString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoordinatorsMicroservice.Models.StudentsPlacementDetails", b =>
                {
                    b.Property<int>("PlacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlacementCompanyI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementCompanyII")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementTypeI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementTypeII")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlacementId");

                    b.ToTable("StudentsPlacementDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
